name: CI Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:

  docker:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  scale-up:
    needs: docker
    uses: ./.github/workflows/scale-ecs.yml
    with:
      desired_count: "1"
    secrets: inherit

  terraform:
    needs: scale-up
    uses: ./.github/workflows/terraform-apply.yml
    secrets: inherit