name: CI Deploy

on:
  workflow_dispatch:
    inputs:
      up_minutes:
        description: "How many minutes should ECS stay up?"
        required: true
        default: "30"
        type: string
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:

  docker:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  debug-docker-outputs:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Print docker outputs
        run: |
          echo "frontend=${{ needs.docker.outputs.frontend_image }}"
          echo "shoppingassistantservice=${{ needs.docker.outputs.shoppingassistantservice_image }}"
          echo "recommendationservice=${{ needs.docker.outputs.recommendationservice_image }}"
          echo "loadgenerator=${{ needs.docker.outputs.loadgenerator_image }}"
          echo "shippingservice=${{ needs.docker.outputs.shippingservice_image }}"
          echo "checkoutservice=${{ needs.docker.outputs.checkoutservice_image }}"
          echo "currencyservice=${{ needs.docker.outputs.currencyservice_image }}"
          echo "productcatalogservice=${{ needs.docker.outputs.productcatalogservice_image }}"
          echo "cartservice=${{ needs.docker.outputs.cartservice_image }}"
          echo "adservice=${{ needs.docker.outputs.adservice_image }}"
          echo "emailservice=${{ needs.docker.outputs.emailservice_image }}"
          echo "paymentservice=${{ needs.docker.outputs.paymentservice_image }}"

  generate-tfvars:
    needs: docker
    uses: ./.github/workflows/generate_tfvars.yml
    with:
      frontend_image: ${{ needs.docker.outputs.frontend_image }}
      shoppingassistantservice_image: ${{ needs.docker.outputs.shoppingassistantservice_image }}
      recommendationservice_image: ${{ needs.docker.outputs.recommendationservice_image }}
      loadgenerator_image: ${{ needs.docker.outputs.loadgenerator_image }}
      shippingservice_image: ${{ needs.docker.outputs.shippingservice_image }}
      checkoutservice_image: ${{ needs.docker.outputs.checkoutservice_image }}
      currencyservice_image: ${{ needs.docker.outputs.currencyservice_image }}
      productcatalogservice_image: ${{ needs.docker.outputs.productcatalogservice_image }}
      cartservice_image: ${{ needs.docker.outputs.cartservice_image }}
      adservice_image: ${{ needs.docker.outputs.adservice_image }}
      emailservice_image: ${{ needs.docker.outputs.emailservice_image }}
      paymentservice_image: ${{ needs.docker.outputs.paymentservice_image }}
    secrets: inherit

  # scale-up:
  #   needs: docker
  #   uses: ./.github/workflows/scale-ecs.yml
  #   with:
  #     desired_count: "1"
  #   secrets: inherit

  terraform:
    needs: generate-tfvars
    uses: ./.github/workflows/terraform-plan-apply.yml
    with:
      apply: true
    secrets: inherit

  scale-up:
    needs: terraform
    uses: ./.github/workflows/scale-down-up-ecs.yml
    with:
      desired_count: "1"
    secrets: inherit

  wait:
    needs: scale-up
    runs-on: ubuntu-latest
    steps:
      - name: Wait for requested minutes
        run: |
          MINUTES="${{ github.event.inputs.up_minutes || '30' }}"
          echo "Waiting for $MINUTES minute(s)..."
          sleep $((MINUTES * 60))

  scale-down:
    needs: wait
    uses: ./.github/workflows/scale-down-up-ecs.yml
    with:
      desired_count: "0"
    secrets: inherit          