name: Docker Build and Push

on:
  workflow_call:
    outputs:
      adservice_image:
        description: adservice image URI
        value: ${{ jobs.build-push.outputs.adservice_image }}
      cartservice_image:
        description: cartservice image URI
        value: ${{ jobs.build-push.outputs.cartservice_image }}
      checkoutservice_image:
        description: checkoutservice image URI
        value: ${{ jobs.build-push.outputs.checkoutservice_image }}
      currencyservice_image:
        description: currencyservice image URI
        value: ${{ jobs.build-push.outputs.currencyservice_image }}
      emailservice_image:
        description: emailservice image URI
        value: ${{ jobs.build-push.outputs.emailservice_image }}
      frontend_image:
        description: frontend image URI
        value: ${{ jobs.build-push.outputs.frontend_image }}
      loadgenerator_image:
        description: loadgenerator image URI
        value: ${{ jobs.build-push.outputs.loadgenerator_image }}
      paymentservice_image:
        description: paymentservice image URI
        value: ${{ jobs.build-push.outputs.paymentservice_image }}
      productcatalogservice_image:
        description: productcatalogservice image URI
        value: ${{ jobs.build-push.outputs.productcatalogservice_image }}
      recommendationservice_image:
        description: recommendationservice image URI
        value: ${{ jobs.build-push.outputs.recommendationservice_image }}
      shippingservice_image:
        description: shippingservice image URI
        value: ${{ jobs.build-push.outputs.shippingservice_image }}
      shoppingassistantservice_image:
        description: shoppingassistantservice image URI
        value: ${{ jobs.build-push.outputs.shoppingassistantservice_image }}

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: dev

    outputs:
      adservice_image: ${{ steps.adservice-meta.outputs.image }}
      cartservice_image: ${{ steps.cartservice-meta.outputs.image }}
      checkoutservice_image: ${{ steps.checkoutservice-meta.outputs.image }}
      currencyservice_image: ${{ steps.currencyservice-meta.outputs.image }}
      emailservice_image: ${{ steps.emailservice-meta.outputs.image }}
      frontend_image: ${{ steps.frontend-meta.outputs.image }}
      loadgenerator_image: ${{ steps.loadgenerator-meta.outputs.image }}
      paymentservice_image: ${{ steps.paymentservice-meta.outputs.image }}
      productcatalogservice_image: ${{ steps.productcatalogservice-meta.outputs.image }}
      recommendationservice_image: ${{ steps.recommendationservice-meta.outputs.image }}
      shippingservice_image: ${{ steps.shippingservice-meta.outputs.image }}
      shoppingassistantservice_image: ${{ steps.shoppingassistantservice-meta.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-terraform-deploy
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug env
        run: |
            echo "ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}"

      - name: Build and push frontend
        id: frontend
        uses: docker/build-push-action@v6
        with:
          context: ./src/frontend
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/frontend-dev:${{ github.sha }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      - name: Export frontend image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/frontend-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: frontend-meta

      - name: Build and push checkoutservice
        id: checkoutservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/checkoutservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/checkoutservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=checkoutservice
          cache-to: type=gha,mode=max,scope=checkoutservice

      - name: Export checkoutservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/checkoutservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: checkoutservice-meta

      - name: Build and push productcatalogservice
        id: productcatalogservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/productcatalogservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/productcatalogservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=productcatalogservice
          cache-to: type=gha,mode=max,scope=productcatalogservice

      - name: Export productcatalogservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/productcatalogservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: productcatalogservice-meta

      - name: Build and push cartservice
        id: cartservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/cartservice/src
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/cartservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=cartservice
          cache-to: type=gha,mode=max,scope=cartservice

      - name: Export cartservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/cartservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: cartservice-meta

      - name: Build and push currencyservice
        id: currencyservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/currencyservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/currencyservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=currencyservice
          cache-to: type=gha,mode=max,scope=currencyservice

      - name: Export currencyservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/currencyservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: currencyservice-meta

      - name: Build and push emailservice
        id: emailservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/emailservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/emailservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=emailservice
          cache-to: type=gha,mode=max,scope=emailservice

      - name: Export emailservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/emailservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: emailservice-meta

      - name: Build and push paymentservice
        id: paymentservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/paymentservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/paymentservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=paymentservice
          cache-to: type=gha,mode=max,scope=paymentservice

      - name: Export paymentservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/paymentservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: paymentservice-meta

      - name: Build and push recommendationservice
        id: recommendationservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/recommendationservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/recommendationservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=recommendationservice
          cache-to: type=gha,mode=max,scope=recommendationservice

      - name: Export recommendationservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/recommendationservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: recommendationservice-meta

      - name: Build and push shippingservice
        id: shippingservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/shippingservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/shippingservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=shippingservice
          cache-to: type=gha,mode=max,scope=shippingservice

      - name: Export shippingservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/shippingservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: shippingservice-meta

      - name: Build and push adservice
        id: adservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/adservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/adservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=adservice
          cache-to: type=gha,mode=max,scope=adservice

      - name: Export adservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/adservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: adservice-meta

      - name: Build and push loadgenerator
        id: loadgenerator
        uses: docker/build-push-action@v6
        with:
          context: ./src/loadgenerator
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/loadgenerator-dev:${{ github.sha }}
          cache-from: type=gha,scope=loadgenerator
          cache-to: type=gha,mode=max,scope=loadgenerator

      - name: Export loadgenerator image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/loadgenerator-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: loadgenerator-meta

      - name: Build and push shoppingassistantservice
        id: shoppingassistantservice
        uses: docker/build-push-action@v6
        with:
          context: ./src/shoppingassistantservice
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/shoppingassistantservice-dev:${{ github.sha }}
          cache-from: type=gha,scope=shoppingassistantservice
          cache-to: type=gha,mode=max,scope=shoppingassistantservice

      - name: Export shoppingassistantservice image URI
        run: echo "image=${{ steps.login-ecr.outputs.registry }}/shoppingassistantservice-dev:${{ github.sha }}" >> "$GITHUB_OUTPUT"
        id: shoppingassistantservice-meta

      - name: Debug values
        run: 
          echo "frontend=${{ steps.frontend-meta.outputs.image }}"
          echo "shoppingassistantservice=${{ steps.shoppingassistantservice-meta.outputs.image }}"
          echo "recommendationservice=${{ steps.recommendationservice-meta.outputs.image }}"
          echo "loadgenerator=${{ steps.loadgenerator-meta.outputs.image }}"